application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      d365-app-builder:
        license: Apache-2.0
        actions:
          newsletter-mailchimp:
            function: actions/newsletter-mailchimp/index.js
            web: 'no'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              MAILCHIMP_API_KEY: $MAILCHIMP_API_KEY
              MAILCHIMP_SERVER: $MAILCHIMP_SERVER
              MAILCHIMP_LIST_ID: $MAILCHIMP_LIST_ID
            annotations:
              require-adobe-auth: false
              final: true